- hosts: all
  gather_facts: yes
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  become: true
  tasks:  
      - name: Simple Example
        roles:
          - role: elastic.elasticsearch
        vars:
          es_version: 7.17.0         